first_project/first_app/urls.py
from django.urls import path
from .views import home,detail,category
app_name="first_app"
urlpatterns = [
    path("", home ,name="test_app"),
    path("page/<int:page>", home ,name="test_app"),
    path("article/<slug:slug>", detail ,name="detail"),
    path("category/<slug:slug>", category ,name="category"),
    path("category/<slug:slug>/page/<int:page>", category ,name="category"),
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('first_app.urls'))
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

first_project/first_app/models.py
from django.db import models
from django.utils import timezone
from extensions.utils import jalali_converter

#managers
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status="p")

class Category(models.Model):
    parent=models.ForeignKey('self',default=None,null=True,blank=True,on_delete=models.SET_NULL,related_name='children',verbose_name='زیر دسته')
    title=models.CharField(max_length=255,verbose_name='عنوان دسته بندی')
    slug=models.SlugField(max_length=255,unique=True,verbose_name='آدرس دسته بندی')
    status=models.BooleanField(default=True,verbose_name='نمایش داده شود؟')
    position=models.IntegerField(verbose_name='پوزیشن')

    class Meta:
        verbose_name="دسته بندی"
        verbose_name_plural="دسته بندی ها"
        ordering=['-parent__id','-position']

    def __str__(self):
        return self.title

    
    

class Article(models.Model):
    choises = (
        ('d', 'پیش نویس'),
        ('p', 'منتشر شده'),
    )
    title = models.CharField(max_length=255,verbose_name='تیتر مقاله')
    slog = models.SlugField(max_length=255, unique=True,verbose_name='آدرس مقاله')
    description = models.TextField(verbose_name='محتوا')
    thumbnail = models.ImageField(upload_to='images',verbose_name='تصویر')
    published = models.DateTimeField(default=timezone.now,verbose_name='تاریخ انتشار')
    created = models.DateTimeField(auto_now=True,verbose_name='زمان ساخت')
    updated = models.DateTimeField(auto_now=True,verbose_name='زمان ویرایش')
    status = models.CharField(max_length=1, choices=choises,verbose_name='وضعیت')
    category=models.ManyToManyField(Category,verbose_name='دسته بندی',related_name='articles')
    
    def __str__(self):
        return self.title
    class Meta:
        verbose_name="مقاله"
        verbose_name_plural="مقالات"
        ordering=['-published']
    def jpublished(self):
        return jalali_converter(self.published)

    jpublished.short_description='زمان انتشار'

    def category_published(self):
        return self.category.filter(status=True)

    
    objects=ArticleManager()

first_project/first_app/views.py
from django.core.paginator import Paginator

from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse, JsonResponse,Http404
from .models import Article,Category



# Create your views here.

def home(request,page=1):
    articles_list=Article.objects.published()
    paginator=Paginator(articles_list,2)
    articles=paginator.get_page(page)
    context = {
        'articles': articles,
    }
    return render(request, "blog/home.html", context=context)


def detail(request, slug):
    context = {
        'article': get_object_or_404(Article.objects.published(),slog=slug)
    }
    return render(request, "blog/detail.html", context=context)


def category(request,slug,page=1):
    category=get_object_or_404(Category,slug=slug,status=True)
    articles_list=category.articles.published()
    paginator = Paginator(articles_list, 2)
    articles = paginator.get_page(page)
    context={
        'category':category,
        'articles':articles
    }
    return render(request,'blog/category.html',context=context)

first_project/first_app/templates/blog/about.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Clean Blog - Start Bootstrap Theme</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="css/clean-blog.min.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="home.html">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="home.html">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="about.html">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="detail.html">Sample Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="contact.html">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/about-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>About Me</h1>
            <span class="subheading">This is what I do.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Custom scripts for this template -->
  <script src="js/clean-blog.min.js"></script>

</body>

</html>

first_project/first_app/templates/blog/base.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">


    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>first app {% block title %}{% endblock %}</title>


        <!-- Bootstrap core CSS -->
        <link href="{% static 'blog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- Custom fonts for this template -->
        <link href="{% static 'blog/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
        <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet'
              type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
              rel='stylesheet' type='text/css'>

        <!-- Custom styles for this template -->
        <link href="{% static 'blog/css/clean-blog.min.css' %}" rel="stylesheet">
        <link href="{% static 'blog/css/rtl.css' %}" rel="stylesheet">

    </head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="{% url 'first_app:test_app' %}">{% title %}</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        {% category_navbar %}
    </div>
</nav>


{% block main %}
{% endblock %}
<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
            </div>
        </div>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'blog/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'blog/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Custom scripts for this template -->
<script src="{% static 'blog/js/clean-blog.min.js' %}"></script>

</body>

</html>
</title>
</head>
<body>

</body>
</html>

first_project/first_app/templates/blog/category.html
{% extends 'blog/base.html' %}
{% load static %}
{% block main %}
<!-- Page Header -->
<header class="masthead" style="background-image: url('{% static " blog/img/home-bg.jpg" %}')">
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
                <h1>my blog</h1>
            </div>
        </div>
    </div>
</div>
</header>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            <h3 class="alert alert-primary text-center">دسته بندی: {{ category.title }}</h3>
            {% for article in category.articles.published %}
            <div class="post-preview">
                <a href="{% url 'first_app:detail' article.slog %}">
                    <h2 class="post-title">
                        {{ article.title }}
                    </h2>
                    <h3 class="post-subtitle">
                        {{ article.description|truncatewords:20 }}
                    </h3>
                </a>
                <p class="post-meta">نوشته شده توسط:
                    <!--                    <a href="#">Start Bootstrap</a>-->
                    {{ article.jpublished }}</p>
                <div>
                    {% for cat in article.category_published.published %}
                    <a href="{% url 'first_app:category' cat.slug %}">{{cat.title}}</a>
                    {% endfor %}
                </div>
            </div>
            <hr>
            {% endfor %}
            <!-- Pager -->
            <div class="clearfix pager-bottom">
                {% if articles.has_next %}
                <a class="btn btn-primary float-right ml-3"
                   href="{% url 'first_app:category' category.slug articles.next_page_number %}"> &rarr; نمایش پست های
                    قدیمی</a>
                {% endif %}

                {% if articles.has_previous %}
                <a class="btn btn-primary float-right"
                   href="{% url 'first_app:category' category.slug articles.previous_page_number %}"> &larr; نمایش پست
                    های جدید </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<hr>
{% endblock %}

first_project/first_app/templates/blog/contact.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Clean Blog - Start Bootstrap Theme</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="css/clean-blog.min.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="home.html">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="home.html">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="about.html">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="detail.html">Sample Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="contact.html">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/contact-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Contact Me</h1>
            <span class="subheading">Have questions? I have answers.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
        <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
        <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
        <!-- To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
        <form name="sentMessage" id="contactForm" novalidate>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Name</label>
              <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Email Address</label>
              <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <label>Phone Number</label>
              <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Message</label>
              <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <br>
          <div id="success"></div>
          <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
        </form>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Contact Form JavaScript -->
  <script src="js/jqBootstrapValidation.js"></script>
  <script src="js/contact_me.js"></script>

  <!-- Custom scripts for this template -->
  <script src="js/clean-blog.min.js"></script>

</body>

</html>

first_project/first_app/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %} | {{ article.title }} {% endblock %}
{% block main %}
<!-- Page Header -->
<header class="masthead" style="background-image: url({{ article.thumbnail.url }})">
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto text-justify">
            <div class="site-heading text-justify">
                <h1>{{article.title}}</h1>
                <time>{{ article.jpublished }}</time>
                <span class="subheading">A Blog Theme by Start Bootstrap</span>
            </div>
        </div>
    </div>
</div>
</header>

<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto text-justify">
                {{ article.description|linebreaks }}
            </div>
        </div>
    </div>
</article>

<hr>
{% endblock %}

first_project/first_app/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}
{% block main %}
<!-- Page Header -->
<header class="masthead" style="background-image: url('{% static "blog/img/home-bg.jpg" %}')">
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
                <h1>my blog</h1>
            </div>
        </div>
    </div>
</div>
</header>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">

            {% for article in articles %}
                <div class="post-preview">
                <a href="{% url 'first_app:detail' article.slog %}">
                    <h2 class="post-title">
                        {{ article.title }}
                    </h2>
                    <h3 class="post-subtitle">
                       {{ article.description|truncatewords:20 }}
                    </h3>
                </a>
                <p class="post-meta">نوشته شده توسط:
<!--                    <a href="#">Start Bootstrap</a>-->
                    {{ article.jpublished }}</p>
                    <div>
                        {% for cat in article.category_published.all %}
                        <a href="{% url 'first_app:category' cat.slug %}">{{cat.title}}</a>
                        {% endfor %}
                    </div>
            </div>
            <hr>
            {% endfor %}
            <!-- Pager -->
            <div class="clearfix pager-bottom">
                {% if articles.has_next %}
                    <a class="btn btn-primary float-right ml-3" href="{% url 'first_app:test_app' articles.next_page_number %}"> &rarr;  نمایش پست های قدیمی</a>
                {% endif %}

                {% if articles.has_previous %}
                    <a class="btn btn-primary float-right" href="{% url 'first_app:test_app' articles.previous_page_number %}"> &larr; نمایش پست های جدید </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<hr>
{% endblock %}

first_project/first_app/templates/blog/partials/category_loop.html
<ul class="navbar-nav ml-auto">
    {% for cat in cat.children.all %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'first_app:category' cat.slug %}">{{ cat.title }}</a>
            {% if cat.children.all %}
                {% include 'blog/partials/category_loop.html' %}
            {% endif %}
        </li>
    {% endfor %}
</ul>

first_project/first_app/templates/blog/partials/hategory_navbar.html
<div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'first_app:test_app' %}">خانه</a>
        </li>
        {% for cat in category %}
        {% if cat.parent == none %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'first_app:category' cat.slug %}">{{ cat.title }}</a>
            {% if cat.children.all %}
                {% include 'blog/partials/category_loop.html' %}
            {% endif %}
        </li>
        {% endif %}
        {% endfor %}

    </ul>
</div>